### ISSUE TITLE
Falta definición del método

### ISSUE THREAD

**Issue by reivajd** [odoo-mastercore/odoo-venezuela#1]
https://github.com/odoo-mastercore/odoo-venezuela/blob/9bf90ace44ce2a63a24ce92474b1fd061b5c724f/l10n_ve_account_withholding/models/account_payment_group.py#L55go

Hola he estado buscando la definición del método **create_payment_withholdings** más sin embargo solo logre conseguirlo en el módulo: 
https://github.com/odoo-mastercore/odoo-venezuela/blob/9bf90ace44ce2a63a24ce92474b1fd061b5c724f/l10n_ve_account_withholding_automatic/models/account_tax.py#L122

Pero el mismo no hace parte de las dependencias del módulo anterior.

https://github.com/odoo-mastercore/odoo-venezuela/blob/9bf90ace44ce2a63a24ce92474b1fd061b5c724f/l10n_ve_account_withholding/__manifest__.py#L30

Saludos,

**Comment by odoo-mastercore** [comment]
Saludos @reivajd !

Gracias por reportar el issue, pasamos a revisión.

@rhe-mastercore FYI

**Comment by rhe-mastercore** [comment]
Saludos @reivajd !!
Gracias por el aporte  esa función es propia del modulo **l10n_ve_withholding_automatic**, más sin embargo existía un archivo que no se utilizaba pero estaba dentro del modulo **l10n_ve_account_withholding**  [aca](https://github.com/odoo-mastercore/odoo-venezuela/commit/fb4b2eeec76f2e7be6c9ce7605c64e1d40962ea9) esta el FIX de eso, procedemos a cerrar el ticket, Slds.

FYI
@odoo-mastercore 
@far-mastercore
