### ISSUE TITLE
Total en Facturas no aparece

### ISSUE THREAD

**Issue by luismata01** [odoo-mastercore/odoo-venezuela#10]
La totalización en el reporte de factura no aparece en el archivo PDF ni en HTML

**Comment by rhe-mastercore** [comment]
Hola @luismata01 !!
Un gusto saludarte, podrías indicarnos mas detalles sobre el problema, Slds.

**Comment by luismata01** [comment]
Hola buenas tardes

Al instalar la  app para la factura de Venezuela,  todo va bien solo que al
imprimir tanto  en pdf como como html no muestra la sección de totales al
final de la hoja.

Sino es molestia podrían indicarme como funciona el N⁹ de control para que
pueda ser cambiado también a la hora de imprimir.

Muchas gracias

**Comment by rhe-mastercore** [comment]
@luismata01 
El numero de control esta dentro de cada diario de ventas, su configuración es independiente, con el tema de los totales podrías adjuntar una imagen del problema, pues el formato por defecto esta cubierto con nuestra localización, Slds.

**Comment by luismata01** [comment]
Anexo lo solicitado 

![image](https://user-images.githubusercontent.com/43929688/136205552-e745c078-19bc-463d-92d3-c925efcb8bc4.png)

**Comment by rhe-mastercore** [comment]
Hola @luismata01 !!! 
Lo que esta pasando alli es que tienes que ajustar tu tipo de letra en el reporte, es decir el tamaño de la misma porque debería estar abajo de eso la tabla con los montos, avísame como te va con eso, Slds.

**Comment by rhe-mastercore** [comment]
Hola @luismata01 !!!
Coméntame si te funciono la solución para proceder a cerra el issues, Slds.
