### ISSUE TITLE
Nro. de Control

### ISSUE THREAD

**Issue by luismata01** [odoo-mastercore/odoo-venezuela#11]
Por favor podrían explicarme como actualizar el Nro. de Control. He tratado de buscar este desde la vista de Diarios de Ventas pero no consigo como.

Agradecido de antemano

**Comment by rhe-mastercore** [comment]
Hola @luismata01 !! 
Te recomiendo para futuros issues antes del titulo poner en corchetes la versión afectado por ejemplo 
`[13.0] Nro. de Control`

Por otro lado como te indicaba en issues anteriores dentro del diario esta la configuracion para el numero de contol, te adjunto una imagen, Slds.
![Captura de pantalla de 2021-10-06 13-01-41](https://user-images.githubusercontent.com/35534162/136250570-b74b48e3-be18-4963-ac17-a7e00bfd307a.png)

**Comment by luismata01** [comment]
De acuerdo con la recomendación, lo que reporte es respecto a la v14. No se parece a lo mostrado en la v13

![image](https://user-images.githubusercontent.com/43929688/136287947-acaab119-3268-45a7-830c-f7ae736bdf6e.png)

**Comment by odoo-mastercore** [comment]
hola @luismata01 !!!
Para versión 14 esta disponible en este [Commit](https://github.com/odoo-mastercore/odoo-venezuela/commit/ed257ef2b2f9ddb33df3b81a402894389f650511)  verifica si tienes la ultima versión, Slds.

**Comment by luismata01** [comment]
Listo ya entendido y corregido el problema, hacía falta actualizar el módulo. Muchas gracias por el apoyo.
![image](https://user-images.githubusercontent.com/43929688/136300776-e4cfaae9-4046-4f57-afa8-27c5e83958d4.png)

**Comment by luismata01** [comment]
Gracias @rhe-mastercore  por el apoyo oportuno y por el gran aporte que están haciendo con esta Localización para nuestro país.

**Comment by rhe-mastercore** [comment]
Chevere @luismata01, abierta la invitación a  que todos colaboremos, Slds.
