### ISSUE TITLE
[14.0] Retenciones

### ISSUE THREAD

**Issue by luismata01** [odoo-mastercore/odoo-venezuela#12]
Buen día

Por favor podrían indicar  la manera correcta o los parámetros requeridos para hacer funcionar el módulo de retenciones de manera correcta.

Gracias de antemano.

**Comment by odoo-mastercore** [comment]
Hola @luismata01 podrias indicarnos cual es tu duda en especifico? que tipo de retención, te comentamos que en lineas generales debes de cargar toda la información fiscal del cliente/proveedor en la sección de contactos y luego al momento del pago del lado izquierdo del formulario te salen las opciones para las retenciones.

**Comment by rubempro** [comment]
Saludos a todos.

Tengo Odoo 15 comunity instalado. Ahora me enteré que soy agente de retención para el SENIAT. No sé por dónde empezar para poder retener el pago de de facturas a proveedores en odoo15. Yo ya he parametrización y personalizado algunas cosas en odoo15, pero al respecto de las retenciones no se por dónde iniciar. 
Gracias por cualquier información o tutorial que le pueda ayudar
