### ISSUE TITLE
no permite instalar l10n_ve_vat_ledger

### ISSUE THREAD

**Issue by octilus** [odoo-mastercore/odoo-venezuela#14]
Cada vez que trat de instalar el vat ledger da un rror de que faltan los archivos TypeError: Model 'report.l10n_ve_vat_ledger.account_vat_ledger_xlsx' inherits from non-existing model 'report.report_xlsx.abstract'.
Si pudieran ayudarme en esa parte agradeceria.

**Comment by rhe-mastercore** [comment]
Hola @octilus cuando levantes un issues por favor indica entre [] que versión se ve afectada por ejemplo [13.0] para tener mayor precisión del caso, por otro lado eso esta fallando porque falta una dependencia que es el modulo Base report_xlsx
 [report_xlsx](https://apps.odoo.com/apps/modules/11.0/report_xlsx/) , quedo atento, Slds.

**Comment by octilus** [comment]
Tiene toda la razon en ambas cosas, no explique que era para odoo 14 version community y no tenia instalado el base report xls.
Error de novato, aprendiendo a usar la herramienta. A pesar de haber vendido algunos ya, me estoy interesando en profundizar y personalizar mas este producto
Saludos cordiales
Marlon Caballero
Octilus Latinoamericana
