### ISSUE TITLE
[v15ce] Error en cálculo de retenciones

### ISSUE THREAD

**Issue by luismata01** [odoo-mastercore/odoo-venezuela#15]
Buen día, 

Al momento de tratar de calcular Retenciones, se origina el siguiente error

UnboundLocalError: local variable 'selected_finacial_debt' referenced before assignment

![image](https://user-images.githubusercontent.com/43929688/174485080-470fb1a2-b5b6-4634-9094-85302fb512d8.png)

Saludos

**Comment by odoo-mastercore** [comment]
Buen día @luismata01, te comentamos que no logramos replicar este error, por favor asegúrate que tengas los repositorios correctos de los cuales depende el proyecto, Saludos.
