### ISSUE TITLE
Modulos Faltantes

### ISSUE THREAD

**Issue by erik21111111** [odoo-mastercore/odoo-venezuela#18]
Hola buenas tardes, estuve intentando usar los modulos pero me saltan errores, por ejemplo, a la hora de instalarlo me dice que Faltan modulos dependientes, como por ejemplo el de account_witthholding_automatic o account_payment_group y no me termina de instalar los modulos faltantes, solo el modulo base. ademas de algunas dependencias que por ejemplo no me aparecen.

**Comment by odoo-mastercore** [comment]
@erik21111111 tiene como dependencia https://github.com/ingadhoc/account-payment y https://github.com/ingadhoc/account-financial-tools

**Comment by erik21111111** [comment]
Muchas gracias. Voy a probar y cualquier cosa vuelvo a escribir :D

**Comment by erik21111111** [comment]
Una ultima duda, logre instalar el  modulo de withholding pero cuando instalo el ultimo modulo que es Localización Vat Ledger Venezuela me sale que necesito el report.xlsx... pero ese no viene en los repositorios, o si?

**Comment by rhe-mastercore** [comment]
Hola @erik21111111 que bueno que lograste instalar mira ese módulo está acá https://github.com/OCA/reporting-engine
Cualquier cosa estamos atentos a tus comentarios, slds.

**Comment by erik21111111** [comment]
Muchisimas gracias por la ayuda, ya por fin estamos probando todo.
