### ISSUE TITLE
Porcentaje incorrecto

### ISSUE THREAD

**Issue by reivajd** [odoo-mastercore/odoo-venezuela#2]
https://github.com/odoo-mastercore/odoo-venezuela/blob/9bf90ace44ce2a63a24ce92474b1fd061b5c724f/l10n_ve_withholding/data/seniat_tabla_islr.xml#L504

Hola buenas noches,
Según Gaceta Oficial Nro. 36203, Decreto 1808, Art.9, Numeral 15:
"Los pagos correspondientes a gastos de transporte conformados por fletes pagados a personas jurídicas a cualquier persona o comunidad constituida y domiciliada en el pais"

para persona jurídica domiciliada es del 3%

Saludos,

[GACETAOFICIAL36203_decreto1808regparleyislr_retenci.pdf](https://github.com/odoo-mastercore/odoo-venezuela/files/5922894/GACETAOFICIAL36203_decreto1808regparleyislr_retenci.pdf)

**Comment by rhe-mastercore** [comment]
Hola @reivajd !! 
desde la apertura de este issues a la fecha han pasado varias actualizaciones ya fue subsanado el problema, por favor cierra el issues, Slds.
