### ISSUE TITLE
where can i download the dependencies for odoo 16 / de donde puedo descargar las dependencias para odoo 16

### ISSUE THREAD

**Issue by discapacidad5** [odoo-mastercore/odoo-venezuela#20]
Depdende de los modulos:
account_payment_group
account_witthholding
account_witthholding_automatic

**Comment by rhe-mastercore** [comment]
Hola las dependencias las puedes ubicar en :

https://github.com/odoo-mastercore/account-payment. 
https://github.com/odoo-mastercore/account-financial-tools

Saludos.

**Comment by discapacidad5** [comment]
> Hola las dependencias las puedes ubicar en :
> 
> https://github.com/odoo-mastercore/account-payment. https://github.com/odoo-mastercore/account-financial-tools
> 
> Saludos.

hola saludos gracias por responder intente instalar y cuando  voy a instalar el primer paquete me sale este mensaje

`Intenta instalar el módulo 'account_payment_group' que depende del módulo 'l10n_latam_account_sequence'.
Este último módulo no está disponible en su sistema.`

pero no consiigo l10n_latam_account_sequence ni aqui ni en los repo de odoo

de antemano muchas gracias por tu ayuda

**Comment by discapacidad5** [comment]
para instalar Account Debt Report me pide 

Intenta instalar el módulo 'account_debt_report' que depende del módulo 'report_aeroo'.
Este último módulo no está disponible en su sistema.

report_aeroo no lo consigo para odoo 16

cuando inntento instalar l10n_ve_withholding me sale este mensaje 
Intenta instalar el módulo 'account_payment_group' que depende del módulo 'l10n_latam_account_sequence'.
Este último módulo no está disponible en su sistema.

**Comment by erik21111111** [comment]
tranquilo hermano, me paso lo mismo dejame subo los archivo a un servidor y te los paso todo junto.

**Comment by erik21111111** [comment]
Aqui está. La localizacion viene al parecer con esas dependencias del comunity y el rhe-mastercore me ayudo, aquí esta https://www.mediafire.com/file/44p1qnffng8zmfh/Demo06-Producci-n.zip/file debes descomprimir y subir todas las carpetas. a mi me toco parte a parte ya que al parecer de subida, github solo permite 100 archivos. Entonces tienes que subirlos de 100 en 100. Espero que te allá servido.

**Comment by discapacidad5** [comment]
> account_payment_group

hola amigo gracias por responder copie todo los archivos y me sige saliendo esto `Intenta instalar el módulo 'account_payment_group' que depende del módulo 'l10n_latam_account_sequence'.
Este último módulo no está disponible en su sistema.`

al parecer neesito este modulo l10n_latam_account_sequence pero no lo consigo en ningun lado 

tabien tego este otro mensaje `Intenta instalar el módulo 'account_debt_report' que depende del módulo 'report_aeroo'.
Este último módulo no está disponible en su sistema.`

al parecer neesito este modulo report_aeroo


agraesco mucho su tiempo  y  ayuda pero realmente nesesito son esos dos modulos si ellos no me deja instalar  y esos modulos no estan disponibles todavia para la vercion 16 ese es el problema se migro el modulo pero no se migraron las dependencias

**Comment by erik21111111** [comment]
no brother, si lo que quieres es la localizacion venezolana con instalar los modulos de la localizacion ya estas hecho. Lo que pasa es que no se porque hay modulos que estan como dependencias pero que no le suman a odoo venezuela. Solo instala los de la Locaclizacion en el orden que sale en github y listo, ya seria todo. Lo demas es configuracion y una mano para agregar o quitar campos.

**Comment by rhe-mastercore** [comment]
Hola @discapacidad5 creo que estas confundido escribeme al ws y te doy una mano, Slds.
+58 424-6255479

**Comment by discapacidad5** [comment]
> no brother, si lo que quieres es la localizacion venezolana con instalar los modulos de la localizacion ya estas hecho. Lo que pasa es que no se porque hay modulos que estan como dependencias pero que no le suman a odoo venezuela. Solo instala los de la Locaclizacion en el orden que sale en github y listo, ya seria todo. Lo demas es configuracion y una mano para agregar o quitar campos.

Bueno lo que pasa es que yo estoy leyendo las instrucciones que están en el repositorio y en las instrucciones me dice que depende de estos módulos que debo instalar primero estos módulos

Depdende de los modulos:
account_payment_group
account_witthholding
account_witthholding_automatic

Esa es la leyenda que tiene el repositorio y yo comienzo instalando esos módulos y es donde me encuentro con esa limitante

**Comment by discapacidad5** [comment]
Gracias a amboos por aclarar @rhe-mastercore y @erik21111111

**Comment by erik21111111** [comment]
Lo lograste?

**Comment by discapacidad5** [comment]
> Lo lograste?

Sí anoche @rhe-mastercore  me ayudó y era que las dependencias son nativas de odoo pero por alguna razón en mi instalación de odoo no estaban esas dependencias y fui al repositorio de odoo y copié la dependencia dentro de mi odoo y problema resuelto si a alguien más le pasa el mismo problema le recomiendo que busque en las aplicaciones nativas de odoo las dependencias faltantes en el repositorio oficial

**Comment by odoo-mastercore** [comment]
Hola @discapacidad5 posiblemente la razón fue que al momento de clonar odoo base no estaban esos módulos. Como práctica recomendada es verificar periódicamente el repo base "odoo/odoo" (y "odoo/enterprise" en caso de usar Enterprise) y realizar pull en la rama que se esté usando (esto podría requerir en algunos casos la actualización de módulos). 

Slds.
