### ISSUE TITLE
Imprimir Account Payment Group

### ISSUE THREAD

**Issue by reivajd** [odoo-mastercore/odoo-venezuela#6]
Error al tratar de imprimir un comprobante de pago de proveedores.

https://gist.github.com/reivajd/251804117af7c280bf32c84dc1a9999f

**Comment by odoo-mastercore** [comment]
Subsanado en este [commit](https://github.com/odoo-mastercore/odoo-venezuela/commit/90ec149a5f7c175e917276d57438952fec5f04aa) Procedemos a cerrar el issues, saludos.
