### ISSUE TITLE
Archivos de traducción faltante

### ISSUE THREAD

**Issue by reivajd** [odoo-mastercore/odoo-venezuela#8]
Falta el archivo de traducción para Venezuela en los siguientes módulos:
- l10n_ve_account_payment_fix
- l10n_ve_account_financial_amount
- l10n_ve_account_payment_group
- l10n_ve_account_payment_group_document
- l10n_ve_account_withholding
- l10n_ve_account_withholding_automatic

**Comment by rhe-mastercore** [comment]
Hola @reivajd ya fueron actualizadas las traducciones de la localización, Slds.

**Comment by nerdop44** [comment]
muchos erres al intertar instalar los modulos en v16, requiero informacion para poder instalar el modulo de forma satisfactoria, gracias

**Comment by rhe-mastercore** [comment]
Hola @nerdop44 como estas? puedes pasarnos unos captures para ayudarte, Slds.

**Comment by nerdop44** [comment]
Muchas gracias por responder.

Estoy instalando el modulo fiscal para venezuela "odoo-venezuela" para odoo
16, desde el branch 16 de su github, al instalar las dependencias me arroja
errores y no me deja avanzar

[image: Captura de pantalla de 2023-04-07 15-01-16.png]


   - account_payment_group

[image: Captura de pantalla de 2023-04-07 15-02-09.png]
[image: Captura de pantalla de 2023-04-07 15-02-26.png]

solo pude instalar

   - territorial_pd

Necesito su ayuda ya que este módulo, según lei, me puede ayudar con el
tema de las retenciones.

     Muchas gracias nuevamente por toda la ayuda que me pueda prestar, si
necesita más informacion con gusto se la puedo enviar con tal que me ayuden
a instalar su módulo.

Nerdo Pulido.

**Comment by odoo-mastercore** [comment]
Hola @nerdop44 como te comento Reydi Para poder ayudarte debes o darnos la traza del error o una imagen para tener la referencia, Saludos.

**Comment by nerdop44** [comment]
Saludos.

   Gracias por responder, ya envié un par de imágenes con el error
completo, espero lo puedan ver y ayudarme, si necesitan con gusto lo envío
de nuevo

**Comment by nerdop44** [comment]
---------- Forwarded message ---------
De: Nerdo pulido ***@***.***>
Date: vie., 7 de abril de 2023 3:10 p. m.
Subject: Re: [odoo-mastercore/odoo-venezuela] Archivos de traducción
faltante (#8)
To: odoo-mastercore/odoo-venezuela <
***@***.***>


Muchas gracias por responder.

Estoy instalando el modulo fiscal para venezuela "odoo-venezuela" para odoo
16, desde el branch 16 de su github, al instalar las dependencias me arroja
errores y no me deja avanzar

[image: Captura de pantalla de 2023-04-07 15-01-16.png]


   - account_payment_group

[image: Captura de pantalla de 2023-04-07 15-02-09.png]
[image: Captura de pantalla de 2023-04-07 15-02-26.png]

solo pude instalar

   - territorial_pd

Necesito su ayuda ya que este módulo, según lei, me puede ayudar con el
tema de las retenciones.

     Muchas gracias nuevamente por toda la ayuda que me pueda prestar, si
necesita más informacion con gusto se la puedo enviar con tal que me ayuden
a instalar su módulo.

Nerdo Pulido.

**Comment by rhe-mastercore** [comment]
Hola @nerdop44 las imágenes no fueron correctamente adjuntadas puedes enviarla al correo rhe@sinapsys.global
